//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Classifies
    {
        public int ClassifyID { get; set; }
        public string ClassifyCode { get; set; }
        public bool StoreDIsplayFlag { get; set; }
        public string ClassifyName { get; set; }
        public string ClassifyNickName { get; set; }
        public int CompanyID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime UpdateDatetime { get; set; }
        public System.DateTime RecordDate { get; set; }
        public bool Visibility { get; set; }
    }
}
