//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Customers
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string LastNameKana { get; set; }
        public string FirstnameKana { get; set; }
        public string Sex { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string ZipCode { get; set; }
        public string Nation { get; set; }
        public string Pref { get; set; }
        public string City { get; set; }
        public string OtherAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public Nullable<int> ClosingDate { get; set; }
        public string Email { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public bool DMFlag { get; set; }
        public bool TouristAgencyFlag { get; set; }
        public Nullable<int> UnpaidAccountID { get; set; }
        public string Note { get; set; }
        public int CompanyID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public System.DateTime RecordDate { get; set; }
        public bool Visibility { get; set; }
    }
}
