//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_BankAccount> M_BankAccount { get; set; }
        public virtual DbSet<M_Companies> M_Companies { get; set; }
        public virtual DbSet<M_Customers> M_Customers { get; set; }
        public virtual DbSet<M_DayDefaultChargeRanks> M_DayDefaultChargeRanks { get; set; }
        public virtual DbSet<M_Deposits> M_Deposits { get; set; }
        public virtual DbSet<M_Employees> M_Employees { get; set; }
        public virtual DbSet<M_Products> M_Products { get; set; }
        public virtual DbSet<M_RoomTypes> M_RoomTypes { get; set; }
        public virtual DbSet<M_StayRooms> M_StayRooms { get; set; }
        public virtual DbSet<M_Stores> M_Stores { get; set; }
        public virtual DbSet<T_ChargeRanks> T_ChargeRanks { get; set; }
        public virtual DbSet<M_Areas> M_Areas { get; set; }
        public virtual DbSet<M_CancelSettings> M_CancelSettings { get; set; }
        public virtual DbSet<M_ChargeOfCustomerAttributes> M_ChargeOfCustomerAttributes { get; set; }
        public virtual DbSet<M_ChargeOfRoomTypes> M_ChargeOfRoomTypes { get; set; }
        public virtual DbSet<M_Classifies> M_Classifies { get; set; }
        public virtual DbSet<M_CustomerAttributes> M_CustomerAttributes { get; set; }
        public virtual DbSet<M_Departments> M_Departments { get; set; }
        public virtual DbSet<M_Districts> M_Districts { get; set; }
        public virtual DbSet<M_EmployeeDepartmentMiddles> M_EmployeeDepartmentMiddles { get; set; }
        public virtual DbSet<M_EmployeePositionMiddles> M_EmployeePositionMiddles { get; set; }
        public virtual DbSet<M_EmployeeStoreMiddles> M_EmployeeStoreMiddles { get; set; }
        public virtual DbSet<M_Fractions> M_Fractions { get; set; }
        public virtual DbSet<M_MealSettings> M_MealSettings { get; set; }
        public virtual DbSet<M_Positions> M_Positions { get; set; }
        public virtual DbSet<M_Role> M_Role { get; set; }
        public virtual DbSet<M_RoomGroups> M_RoomGroups { get; set; }
        public virtual DbSet<M_SerialNumbers> M_SerialNumbers { get; set; }
        public virtual DbSet<M_SpecialDeposits> M_SpecialDeposits { get; set; }
        public virtual DbSet<M_SpecialProducts> M_SpecialProducts { get; set; }
        public virtual DbSet<M_StayChargeKinds> M_StayChargeKinds { get; set; }
        public virtual DbSet<M_StayPlans> M_StayPlans { get; set; }
        public virtual DbSet<M_Taxes> M_Taxes { get; set; }
        public virtual DbSet<M_TaxNotations> M_TaxNotations { get; set; }
        public virtual DbSet<T_CancelCharges> T_CancelCharges { get; set; }
        public virtual DbSet<T_LoginLogs> T_LoginLogs { get; set; }
        public virtual DbSet<T_ProhibitedRooms> T_ProhibitedRooms { get; set; }
        public virtual DbSet<T_SalesBudgets> T_SalesBudgets { get; set; }
        public virtual DbSet<T_SimpleCashRegisterBasicDetails> T_SimpleCashRegisterBasicDetails { get; set; }
        public virtual DbSet<T_SimpleCashRegisterBasics> T_SimpleCashRegisterBasics { get; set; }
        public virtual DbSet<T_SimpleCashRegisterDeposits> T_SimpleCashRegisterDeposits { get; set; }
        public virtual DbSet<T_SimpleCashRegisterDivisions> T_SimpleCashRegisterDivisions { get; set; }
        public virtual DbSet<T_StayAccountBasicDetails> T_StayAccountBasicDetails { get; set; }
        public virtual DbSet<T_StayAccountBasics> T_StayAccountBasics { get; set; }
        public virtual DbSet<T_StayAccountDeposits> T_StayAccountDeposits { get; set; }
        public virtual DbSet<T_StayAccountDivisions> T_StayAccountDivisions { get; set; }
        public virtual DbSet<T_StayAccountPlanProducts> T_StayAccountPlanProducts { get; set; }
        public virtual DbSet<T_StayEditAccountBasicDetails> T_StayEditAccountBasicDetails { get; set; }
        public virtual DbSet<T_StayEditAccountBasics> T_StayEditAccountBasics { get; set; }
        public virtual DbSet<T_StayEditAccountDeposits> T_StayEditAccountDeposits { get; set; }
        public virtual DbSet<T_StayEditAccountDivisions> T_StayEditAccountDivisions { get; set; }
        public virtual DbSet<T_StayFictitiousAccountBasicDetails> T_StayFictitiousAccountBasicDetails { get; set; }
        public virtual DbSet<T_StayFictitiousAccountBasics> T_StayFictitiousAccountBasics { get; set; }
        public virtual DbSet<T_StayFictitiousAccountDeposits> T_StayFictitiousAccountDeposits { get; set; }
        public virtual DbSet<T_StayFictitiousAccountDivisions> T_StayFictitiousAccountDivisions { get; set; }
        public virtual DbSet<T_StayFictitiousAccountPlanProducts> T_StayFictitiousAccountPlanProducts { get; set; }
        public virtual DbSet<T_StayPlanProducts> T_StayPlanProducts { get; set; }
        public virtual DbSet<T_StayReservationBasics> T_StayReservationBasics { get; set; }
        public virtual DbSet<T_StayReservationDetails> T_StayReservationDetails { get; set; }
        public virtual DbSet<T_StayReservationGuestLists> T_StayReservationGuestLists { get; set; }
        public virtual DbSet<T_StayReservationRooms> T_StayReservationRooms { get; set; }
        public virtual DbSet<T_StayReservationRoomTypes> T_StayReservationRoomTypes { get; set; }
        public virtual DbSet<T_StayReservationUseDetails> T_StayReservationUseDetails { get; set; }
        public virtual DbSet<T_StoreBankAccounts> T_StoreBankAccounts { get; set; }
        public virtual DbSet<T_StoreCancelSettings> T_StoreCancelSettings { get; set; }
        public virtual DbSet<T_StoreClassifies> T_StoreClassifies { get; set; }
        public virtual DbSet<T_StoreCustomerAttributes> T_StoreCustomerAttributes { get; set; }
        public virtual DbSet<T_StoreDeposits> T_StoreDeposits { get; set; }
        public virtual DbSet<T_StoreProducts> T_StoreProducts { get; set; }
        public virtual DbSet<T_StoreRoomTypes> T_StoreRoomTypes { get; set; }
        public virtual DbSet<T_StoreStayPlanProducts> T_StoreStayPlanProducts { get; set; }
        public virtual DbSet<T_StoreStayPlans> T_StoreStayPlans { get; set; }
        public virtual DbSet<T_UnpaidAccountBalanceHistories> T_UnpaidAccountBalanceHistories { get; set; }
        public virtual DbSet<T_UnpaidAccounts> T_UnpaidAccounts { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
