//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CancelCharges
    {
        public int CancelChargeID { get; set; }
        public Nullable<int> StoreCancelID { get; set; }
        public Nullable<int> StoreProductID { get; set; }
        public Nullable<int> StayReservationBasicID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> NumberOfProduct { get; set; }
        public Nullable<int> CancelCharge { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<bool> Visibility { get; set; }
    }
}
