//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SimpleCashRegisterBasics
    {
        public int SimpleCashRegisterBasicID { get; set; }
        public Nullable<int> SalesBudgetID { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public Nullable<int> SerialNumberID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> SalesRecordDate { get; set; }
        public Nullable<int> StayNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string ZipCode { get; set; }
        public string Pref { get; set; }
        public string City { get; set; }
        public string OtherAddress { get; set; }
        public string Tell { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> Visibility { get; set; }
    }
}
