//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StayFictitiousAccountBasicDetails
    {
        public int StayFictitiousAccountBasicDetailID { get; set; }
        public Nullable<int> StayFictitiousAccountBasicID { get; set; }
        public Nullable<int> StayReservationBasicID { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> RepresentativeSettlementFlag { get; set; }
        public Nullable<int> StoreStayPlanID { get; set; }
        public Nullable<int> StoreProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> StoreClassifyID { get; set; }
        public Nullable<int> NumberOfProduct { get; set; }
        public Nullable<int> DiscountRate { get; set; }
        public Nullable<int> DiscountCharge { get; set; }
        public Nullable<int> ServiceRate { get; set; }
        public Nullable<int> TaxRate { get; set; }
        public Nullable<int> DivisionNumber { get; set; }
        public Nullable<int> StayAccountDivisionID { get; set; }
        public Nullable<bool> OnTheWayPaymentFlag { get; set; }
        public Nullable<System.DateTime> OnTheWayPaymentDate { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> Visibility { get; set; }
    }
}
