//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StayReservationRoomTypes
    {
        public int StayReservationRoomTypeID { get; set; }
        public Nullable<int> StayReservationBasicID { get; set; }
        public Nullable<int> StayReservationDetailID { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public Nullable<int> StoreRoomTypeID { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<int> PeopleNumber { get; set; }
        public Nullable<int> StayPlanID { get; set; }
        public Nullable<int> StayPlanUnitPrice { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> Visibility { get; set; }
        public string EmployeeID { get; set; }
    }
}
