//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StayReservationUseDetails
    {
        public int StayReservationUseDetailID { get; set; }
        public Nullable<int> StayReservationDetailID { get; set; }
        public Nullable<int> StayReservationBasicID { get; set; }
        public Nullable<int> StayReservationRoomTypeID { get; set; }
        public Nullable<int> StayReservationRoomID { get; set; }
        public string StayReservationRoomCode { get; set; }
        public string StayReservationRoomCodeBranchCode { get; set; }
        public Nullable<int> StayAccountBasicDetailID { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public Nullable<int> StoreStayPlanID { get; set; }
        public Nullable<int> StoreProductID { get; set; }
        public Nullable<int> ProductName { get; set; }
        public Nullable<int> NumberOfProduct { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<int> DiscountCharge { get; set; }
        public Nullable<int> DiscountRate { get; set; }
        public Nullable<int> ServiceRate { get; set; }
        public Nullable<int> TaxRate { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<bool> Visibility { get; set; }
    }
}
