//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StayEditAccountDeposits
    {
        public int StayEditAccountDepositID { get; set; }
        public Nullable<int> StayAccountDepositID { get; set; }
        public Nullable<int> StayEditAccountBasicID { get; set; }
        public Nullable<int> StayReservationBasicID { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> RepresentativeSettlementFlag { get; set; }
        public Nullable<int> StoreDepositID { get; set; }
        public string DepositName { get; set; }
        public Nullable<int> StoreClassifyID { get; set; }
        public Nullable<int> Charge { get; set; }
        public Nullable<bool> InvoicingFlag { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<bool> ReceivableFlag { get; set; }
        public Nullable<System.DateTime> ReceivableDate { get; set; }
        public Nullable<int> UnpaidAccountID { get; set; }
        public Nullable<bool> OnTheWayPaymentFlag { get; set; }
        public Nullable<System.DateTime> OnTheWayPaymentDate { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<bool> Visibility { get; set; }
    }
}
