//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StoreProducts
    {
        public int StoreProductID { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string StoreProductCode { get; set; }
        public string ProductName { get; set; }
        public string KanaName { get; set; }
        public int OriginalPrice { get; set; }
        public int ClassifyID { get; set; }
        public string JANCode { get; set; }
        public string Unit { get; set; }
        public string SpecialProductCode { get; set; }
        public int CompanyID { get; set; }
        public int StoreID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime UpdateDatetime { get; set; }
        public System.DateTime RecordDate { get; set; }
        public bool Visibility { get; set; }
    }
}
