//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UnpaidAccountBalanceHistories
    {
        public int UnpaidAccountBalanceHistoryID { get; set; }
        public Nullable<int> UnpaidAccountID { get; set; }
        public Nullable<int> UnPaidLastMonthCarryoverCharge { get; set; }
        public Nullable<int> OverPaidLastMonthCarryoverCharge { get; set; }
        public Nullable<int> UnPaidCurrentMonthCharge { get; set; }
        public Nullable<int> OverPaidCurrentMonthCharge { get; set; }
        public Nullable<int> UnPaidLastMonthTransferCharge { get; set; }
        public Nullable<int> OverPaidLastMonthTransferCharge { get; set; }
        public Nullable<int> UnPaidLastMonthPaidCharge { get; set; }
        public Nullable<int> UnPaidBalanceCharge { get; set; }
        public Nullable<int> OverPaidBalanceCharge { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
